/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.test.test01.controller;

import com.test.test01.model.Msg;
import com.test.test01.model.Name;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "prod", description = "the prod API")
public interface ProdApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /prod//test : summargInfo
     *
     * @param txcode 交易代码 (required)
     * @param txdate 交易日期 (required)
     * @param name 姓名 (required)
     * @return 返回成功 (status code 200)
     *         or 返回成功 (status code 500)
     */
    @ApiOperation(value = "summargInfo", nickname = "getuserinfo", notes = "", response = Msg.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "返回成功", response = Msg.class),
        @ApiResponse(code = 500, message = "返回成功") })
    @RequestMapping(value = "/prod//test",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Msg> getuserinfo(@ApiParam(value = "交易代码",required=true) @PathVariable("txcode") String txcode,@NotNull @ApiParam(value = "交易日期", required = true) @Valid @RequestParam(value = "txdate", required = true) String txdate,@ApiParam(value = "姓名" ,required=true )  @Valid @RequestBody Name name) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"rcv_acc_no\" : \"rcv_acc_no\", \"rcv_name\" : \"rcv_name\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
